name: Compile and Update Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install LaTeX and dependencies
        run: sudo apt-get update && sudo apt-get install -y latexmk texlive-full

      - name: Pull latest changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main

      - name: Run main.py script
        run: python .github/workflows/main.py

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add, commit and push changes
        run: |
          git add .
          git commit -m "Automated update from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}